#include <iostream>
#include <fstream>
#include <vector>
#include <map>
#include <sstream>
#include <string>
#include <utility>
#include <bitset>
#include <math.h>
#include <exception>
#include <algorithm>